### ISSUE TITLE
How to close the webview & to return to my app

### ISSUE THREAD

**Issue by sarvagayatri** [bradmartin/nativescript-advanced-webview#11]

**Comment by bradmartin** [comment]
I don't recall a method to achieve this. The user has to do this manually. If you have the Twitter app on Android and enable this feature in settings, it uses custom tabs and you'll see the *X* in top left of chrome window to close the activity. I believe iOS is the same. If you find a method to achieve this in the native APIs we can add it. I just don't think there is a way without user action
