### ISSUE TITLE
ReferenceError: co is not definded

### ISSUE THREAD

**Issue by nina514** [bradmartin/nativescript-advanced-webview#28]
When you call the init () function, a "ReferenceError: co is not definded" message is displayed.
I am using nativescript-vue.

```
const AdvancedWebView = require('nativescript-advanced-webview');
AdvancedWebView.init();
```

**Comment by triniwiz** [comment]
🤔 looks like aar file is not being added so it's not finding the class

**Comment by bradmartin** [comment]
Updated plugin and demo, works fine now, sounds like a build issue from the OP
