### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by 7ammer** [bradmartin/nativescript-advanced-webview#33]
I cannot get `nativescript-advanced-webview` to work on android. It does however work on IOS. I am using the Vue.js varient of nativescript.

Here is a working test of the issue:
https://play.nativescript.org/?template=play-vue&id=Ra31Tj&v=2

**Comment by CarlosTolenk** [comment]
It's not working for me either.
I'm doing the implementation with Angular, and when I start it in the main.ts it throws me an error about the init function. I do not know what the problem really is, I tried to put the init inside the app.component and it happens exactly the same.

**Comment by triniwiz** [comment]
@7ammer it will not work on the play site because it uses a custom aar and @CarlosTolenk you need to put that init in the main.ts for angular the app component is a bit late because it takes time to connect to the service

**Comment by CarlosTolenk** [comment]
![desktop screenshot](https://user-images.githubusercontent.com/29358666/41484705-c994170c-70ab-11e8-9002-fa5b5649cd8d.png)
I tried to put in the main.ts and it throws me an error at the moment of building the app, and this happened after adding the plugin .. What is this?

**Comment by triniwiz** [comment]
After you removed the dimensions did you remove the platforms directory in the app root so you will have a fresh build ?
