### ISSUE TITLE
The app is not built since I installed the plugin

### ISSUE THREAD

**Issue by CarlosTolenk** [bradmartin/nativescript-advanced-webview#34]
![image](https://user-images.githubusercontent.com/29358666/41491306-49ba9310-70c6-11e8-99f8-422213241c27.png)

At the time of installing the plugin the application stops working, I am initializing correctly as shown in the documentation but I get an error.

Why does this happen? Will I have to make the reference in the references.d.ts file?

**Comment by triniwiz** [comment]
I’m guessing you are using {N} v4 if yes then the plugin needs to be updated all you need to do for a temp solution is remove the dimension set by the plugin in the plugin directory include.gradle


Sent from Yahoo Mail for iPhone


On Friday, June 15, 2018, 6:04 PM, Carlos Tolentino <notifications@github.com> wrote:




At the time of installing the plugin the application stops working, I am initializing correctly as shown in the documentation but I get an error.

Why does this happen? Will I have to make the reference in the references.d.ts file?

**Comment by CarlosTolenk** [comment]
I have removed the dimensions that are inside the plugin directory and the problem still continues.

**Comment by bradmartin** [comment]
Updated plugin to `3.0.0` and confirmed demo works just now. Try that if you have any issues still.
