### ISSUE TITLE
Breaks build on Android

### ISSUE THREAD

**Issue by chrishaff** [bradmartin/nativescript-advanced-webview#38]
When I install this plugin the build stops working. I remove it it builds again. I reviewed a couple of closed issues that are similar. Unfortunately none of the fixes have worked for me.

I am using:
nativescript 4.1.2 
tns-core-modules 4.1.1
tns-android 4.1.3
Android SDK build tools 27.0.2 (supports appcompat)

This is what I think is the salient portion of the output.

`C:\Users\Chris Haff\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\9b5e00fece4821b56b57b99b7f241c6c\res\values-v26\values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.

C:\Users\Chris Haff\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\9b5e00fece4821b56b57b99b7f241c6c\res\values-v26\values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.

C:\Users\Chris Haff\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\9b5e00fece4821b56b57b99b7f241c6c\res\values-v26\values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.

C:\Users\Chris Haff\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\9b5e00fece4821b56b57b99b7f241c6c\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/fontStyle not found.

C:\Users\Chris Haff\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\9b5e00fece4821b56b57b99b7f241c6c\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/font not found.

C:\Users\Chris Haff\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\9b5e00fece4821b56b57b99b7f241c6c\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/fontWeight not found.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.`

**Comment by chrishaff** [comment]
There are several reports of this same issue on the NativeScript Forum. The most recent from 5 days ago.
https://discourse.nativescript.org/t/execution-failed-for-task-app-processdebugresources/5576

**Comment by yonkoGH** [comment]
same !

**Comment by bradmartin** [comment]
Can someone confirm if this happens when you add ONLY this plugin as a dependency? That would help narrow down if it's the plugin, which I don't think is the case as I had the demo working 2-3 weeks ago (of course google/android changes often so the build tools could be the issue). If someone can report that we'll know if the issue is here or in the android build tools when adding this plugin in a combination of other libraries.

**Comment by yonkoGH** [comment]
Hi Brad
When i remove  the plugin from the project dependencies the android application runs just fine .also couldn't run your demo app on my machine. 

I have android SDK build tools 27.0.1 installed on my mac machine

thank you for your help .

**Comment by chrishaff** [comment]
Yes, this only happens on Android once this plugin is added.
The demo also does not compile.

I have tried Android SDK Build-tools 27.0.1 and 27.0.2.

**Comment by bradmartin** [comment]
<img width="1105" alt="tabsdemo" src="https://user-images.githubusercontent.com/6006148/43682649-7bda7aee-9840-11e8-93c0-0c14878b8934.png">

Demo builds fine for me - If you currently fork/clone and run `cd src && npm run demo.android` it fails? If so then this is some android build issue and not necessarily with the plugin itself I believe, but rather you have this plugin and others conflicting with google/android libs (support library for example).  I'm adding a `Demo` section to the readme to make that step more clear to run the demo.

**Comment by yonkoGH** [comment]
I did what you told us and same thing happened > android build failed 

<img width="811" alt="screen shot 2018-08-05 at 9 46 38 am" src="https://user-images.githubusercontent.com/21172361/43683971-268c7130-9897-11e8-981c-7f31bfaffa10.png">

**Comment by bradmartin** [comment]
I'm fairly confident this is an android build tools issue. What version of the android build tools do you have installed?

**Comment by yonkoGH** [comment]
27.0.2

**Comment by chrishaff** [comment]
@bradmartin What version of Build Tools are you using?

**Comment by bradmartin** [comment]
![these](https://user-images.githubusercontent.com/6006148/43728263-24ca8bce-996a-11e8-9ff0-38f2ecf330a2.png)
 
@yonkoGH - so it looks like 27.0.3 is a valid build-tools version to try bumping for you. I have all the latest installed it looks like from the sdk manager image here ^

**Comment by chrishaff** [comment]
Hey all, I did a little research and learned that you must have "Android Support Repository" and "Google Repository" installed to use appcompat.  This allows me to compile it (using Build Tools 27.0.2)!

@yonkoGH does this solve your build problem also?

Now I've run into [another issue: co is not defined](https://github.com/bradmartin/nativescript-advanced-webview/issues/40).

**Comment by yonkoGH** [comment]
@chrishaff  Works for me now tnx (android-27 was missing ) 
but not as expected see: 
<img width="1661" alt="screen shot 2018-08-07 at 1 35 46 pm" src="https://user-images.githubusercontent.com/21172361/43774925-1d5dd2c4-9a4b-11e8-87c8-626d070c8a13.png">

@bradmartin  does it need "google chrome" to work like the demo .

**Comment by bradmartin** [comment]
yea if you want `ChromeCustomTabs` Chrome will need to be on device. If not it falls back to the stock webview on the device. That should be the behavior 👍 - the android Twitter app uses this same behavior if you want to see it in action. I believe there's even a toggle switch to disable chrome inside twitter app for android, unless it has been removed in the past few months.
