### ISSUE TITLE
Android: co.fitcom.fancywebview.AdvancedWebViewListener is not defined

### ISSUE THREAD

**Issue by chrishaff** [bradmartin/nativescript-advanced-webview#40]
ReferenceError: co is not defined

When I call init() or openAdvancedUrl() I get this error:
`JS: ReferenceError: co is not defined
JS:     at Object.openAdvancedUrl (file:///data/data/org.nativescript.drawertemplate/files/app/tns_modules/nativescript-advanced-webview/advanced-webview.js:29:13)` 

I am using:

- nativescript 4.1.2
- tns-core-modules 4.1.1
- tns-android 4.1.3
- Android SDK build tools 27.0.2

**Comment by bradmartin** [comment]
This is possibly a build issue with adding the plugin. Make sure you `clean` the platforms & node_modules then do a fresh build.
