### ISSUE TITLE
Could not find com.android.support:customtabs:25.0.1.

### ISSUE THREAD

**Issue by stefanjudis** [bradmartin/nativescript-advanced-webview#5]
I could be related to the other two issues there were recently closed, but as I'm a total native noob I didn't find solutions in the issues.

Since version `1.1.2`(this include `1.1.3`) my build is failing.

He is what I do:

```
$ tns --version
2.4.2

$ rm -rf node_modules && npm i && tns platform remove android && tns platform add android && tns deploy android

...
...
...
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'stefanTravel'.
> Could not resolve all dependencies for configuration ':_F0F1F2DebugCompile'.
   > Could not find com.android.support:customtabs:25.0.1.
     Searched in the following locations:
```

Any help is appreciated. :)

**Comment by bradmartin** [comment]
Yep I had this issue when updating the plugin. Just update all of your
android stuff locally. Build tools, sdks, support libs. Everything. Then do
a build. That's the fix bc the update is using the latest custom tabs lib
from Google.

**Comment by stefanjudis** [comment]
> Just update all of your android stuff locally

As said, I just made my way through the nativescript install guide... Is there a quick route telling me what I have to update?

**Comment by bradmartin** [comment]
Sorry :) open a terminal, run `android` this opens the android sdk manager
on your machine (assuming you have android installed) then go through and
make sure you are up to date on build tools, sdks, support lib (at bottom
of list).

**Comment by stefanjudis** [comment]
Cool. It's fixed now.

Thanks a lot for the quick reply. :)
