### ISSUE TITLE
Not loading on iOS 15

### ISSUE THREAD

**Issue by iMarwan-k** [bradmartin/nativescript-advanced-webview#56]
I installed the latest version of the plugin and it is not loading the URL on ios 15. I just get an empty page.

it works good with Android, but with ios it seems like it is just initializing the webview but not loading the URL

![Simulator Screen Shot - iPhone 11 - 2021-11-30 at 17 36 45](https://user-images.githubusercontent.com/19311396/144145166-fa0408ac-bec8-4978-8832-a5496289c067.png)

I tired the following change in advanced-webview.ios.js and now it works

`const app = UIApplication.sharedApplication;
    ctrl = app.keyWindow.rootViewController;`

**Comment by Bezlepkin** [comment]
I have same issue. Works on a fresh install but doesn't work in my app. I have a lot of plugins, I suspect it's the delegate...

**Comment by Bezlepkin** [comment]
![2022-03-17_14-50-05](https://user-images.githubusercontent.com/10475699/158802614-40973e18-aed3-4972-ab05-c939d22fb581.png)

SFSafariViewControllerDelegateImpl.initWithOwnerCallback method is works and that's it. Then the code does not work
@bradmartin

**Comment by bradmartin** [comment]
@Bezlepkin  - what do you mean "that's it"? Removing it or something?

**Comment by codemeall** [comment]
Hi, anyone get to resolve the above issue?

**Comment by Silureth** [comment]
Hi,
Yesterday i faced this problem the solution based on this :[post](https://blog.rizwan.dev/blog/blank_safari_viewcontroller) is to present SafariViewController from rootView.
So the code part in ts (in angular 15, and ns 8.1)
`import { AdvancedWebViewOptions, openAdvancedUrl, NSAdvancedWebViewEventEmitter, AdvancedWebviewEvents } from 'nativescript-advanced-webview'
import { getRootView } from '@nativescript/core/application';
....
const opts: AdvancedWebViewOptions = {
      url: "<yourURL>",
      showTitle: true,
      toolbarColor: '#336699',
      toolbarControlsColor: '#fff',
      ios: {
        viewController: getRootView().viewController
      }

`

**Comment by bradmartin** [comment]
Good find @Silureth  - I'm pushing a bug release of the plugin where the core does the root view controller, but I'll also merge your README PR and add a note that it's not 100% necessary with version x.x.x
