### ISSUE TITLE
Does not work with Angular on iOS

### ISSUE THREAD

**Issue by Bezlepkin** [bradmartin/nativescript-advanced-webview#58]
I tried with NativeScript Plain on an iOS device, everything works!
But if I try on NativeScript Angular, it only works on Android
![2022-03-17_16-48-36](https://user-images.githubusercontent.com/10475699/158822992-e1b2bf30-680b-4953-9b1b-34ca95b586c8.png)
![2022-03-17_16-48-50](https://user-images.githubusercontent.com/10475699/158823002-5d3ad953-991c-4de8-80d6-5d9deb2ef000.png)
.

NativeScript: 8.1.5
@nativescript/core: 8.0.2
@nativescript/angular: 13.0.0
nativescript-advanced-webview: 7.0.1

@bradmartin

**Comment by codemeall** [comment]
@Bezlepkin did you get to resolve this issue? me too getting the same issue

**Comment by Silureth** [comment]
Posted the same in the other issue #56:

Hi,
Yesterday i faced this problem the solution based on this [post](https://blog.rizwan.dev/blog/blank_safari_viewcontroller) is to present SafariViewController from rootView.
So the code part in ts (in angular 15, and ns 8.4)
`
import { AdvancedWebViewOptions, openAdvancedUrl, NSAdvancedWebViewEventEmitter, AdvancedWebviewEvents } from 'nativescript-advanced-webview';
import { getRootView } from '@nativescript/core/application';
`
....
`
const opts: AdvancedWebViewOptions = {
      url: "<yourURL>",
      showTitle: true,
      toolbarColor: '#336699',
      toolbarControlsColor: '#fff',
      ios: {
        viewController: getRootView().viewController
      }
`

**Comment by bradmartin** [comment]
Version 7.0.2 fixes this - or you can use the example provided by @Silureth  on the README
