### ISSUE TITLE
Failed to find module: "nativescript-advanced-webview"

### ISSUE THREAD

**Issue by biblelogosthegame** [bradmartin/nativescript-advanced-webview#8]
An uncaught Exception occurred on "main" thread...
Failed to find module: "nativescript-advanced-webview"

I copied the repo directly from this project and I installed the plugin and as the screenshot shows it is installed, but I'm still getting this error.  I appreciate any help.  Thanks.

![node_modules](https://cloud.githubusercontent.com/assets/23114344/22813158/30310e74-eefe-11e6-946a-7d3b333b61f3.jpg)

![failedtofindmodule](https://cloud.githubusercontent.com/assets/23114344/22813071/a83b1398-eefd-11e6-909c-d9b987a46128.jpg)

**Comment by bradmartin** [comment]
Make sure you follow this for installing plugins: https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/

**Comment by bradmartin** [comment]
Have not been able to reproduce cloning the demo or installing in an app with `tns plugin add` command. If you still have an issue let me know.
