### ISSUE TITLE
Can't run on iOS emulator

### ISSUE THREAD

**Issue by kinggolf** [bradmartin/nativescript-advanced-webview#9]
Thanks @bradmartin: plug-in works super on a device, but not on the emulator. I get this error message: file:///app/tns_modules/nativescript-advanced-webview/advanced-webview.js:15:63: JS ERROR ReferenceError: Can't find variable: SFSafariViewControllerDelegate

I think this might be expected behavior but wanted to check. Thanks again.

**Comment by bradmartin** [comment]
Sorry I missed this @kinggolf - I haven't seen that error on the iOS simulator. Does this simulator have Safari installed?

**Comment by kinggolf** [comment]
Thx @bradmartin I had forgotten about this. I do not see this either, anymore. I am not sure what I was seeing originally, but it is all good now. Let's close and if it comes up again I will re-open.
